image: Ubuntu1804  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew  #добавляем права на запуск
  # запускаем SUT (запоминаем информацию о процессе в переменной $App)
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме (см.ниже)